services:
  - type: web
    name: game-store-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_BASE_URL
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SUPABASE_PROJECT_REF
        value: gcshwfphrgpzvzmosvzf
      - key: SUPABASE_REGION
        value: ap-southeast-1
      - key: SUPABASE_POOLER_MODE
        value: session
