-- Game Store schema for Supabase / PostgreSQL

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username varchar(100) not null unique,
  email varchar(255) not null unique,
  password varchar(255) not null,
  role varchar(20) not null default 'user',
  created_at timestamptz not null default now(),
  display_name varchar(120),
  avatar_url varchar(255),
  bio text,
  favorite_genre varchar(120),
  theme_preference varchar(20) not null default 'dark',
  email_verified_at timestamptz
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title varchar(255) not null unique,
  image text,
  description text,
  category varchar(255),
  price varchar(50) default 'Free',
  media_url text,
  min_requirement text,
  max_requirement text,
  story text,
  rating numeric(3,1)
);

create table if not exists public.library (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  game_id bigint not null references public.games(id) on delete cascade on update cascade,
  added_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  game_id bigint not null references public.games(id) on delete cascade on update cascade,
  added_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create table if not exists public.recently_viewed (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  game_id bigint not null references public.games(id) on delete cascade on update cascade,
  viewed_at timestamptz not null default now(),
  unique (user_id, game_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade on update cascade,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  rating smallint not null,
  review_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, user_id)
);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  name varchar(120) not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.collection_items (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.collections(id) on delete cascade on update cascade,
  game_id bigint not null references public.games(id) on delete cascade on update cascade,
  added_at timestamptz not null default now(),
  unique (collection_id, game_id)
);

create table if not exists public.auth_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  purpose varchar(40) not null,
  token_hash char(64) not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade on update cascade,
  title varchar(160) not null,
  message text not null,
  type varchar(20) not null default 'info',
  link varchar(255),
  is_read smallint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_read on public.notifications (user_id, is_read);
create index if not exists idx_token_user_purpose on public.auth_tokens (user_id, purpose);
create index if not exists idx_recent_game on public.recently_viewed (user_id, game_id);
create index if not exists idx_reviews_game on public.reviews (game_id, user_id);

insert into public.users (id, username, email, password, role, email_verified_at)
values (
  1,
  'admin',
  'admin@gamestore.local',
  '$2y$10$zyQ5I57wcCH4mO44/tAomO4hH0idM9Lw8yb3uhWKmXoKW7841FhEa',
  'admin',
  now()
)
on conflict (id) do update
set username = excluded.username,
    email = excluded.email,
    password = excluded.password,
    role = excluded.role,
    email_verified_at = excluded.email_verified_at;

insert into public.games
(id, title, image, description, category, price, media_url, min_requirement, max_requirement, story, rating)
values
(1, 'Red Dead Redemption 2', 'images/RDR2.jpg', 'Outlaws for life in the dying days of the wild west.', 'Action / Adventure', 'Free', 'Video/RDR 2.mp4', 'OS: Windows 10; CPU: Intel i5-6600K; RAM: 12 GB; GPU: GTX 1060; Storage: 150 GB', 'OS: Windows 10; CPU: Intel i7-8700K; RAM: 16 GB; GPU: RTX 2070; Storage: 150 GB', 'Lead Arthur Morgan and the Van der Linde gang across a changing frontier.', 4.9),
(2, 'Black Myth: Wukong', 'images/Black Myth Wukong.jpeg', 'Unleash your legend in the mythical world of Sun Wukong.', 'Action / RPG', 'Free', 'Video/Black Myth Wukong Trailer .mp4', 'OS: Windows 10; CPU: Intel i5-8400; RAM: 16 GB; GPU: GTX 1060; Storage: 130 GB', 'OS: Windows 10; CPU: Intel i7-9700; RAM: 16 GB; GPU: RTX 3060; Storage: 130 GB', 'A mythic action RPG inspired by Journey to the West.', 4.8),
(3, 'Grand Theft Auto V', 'images/Gta V.jpg', 'Build an empire to stand the test of time.', 'Action / Adventure', 'Free', 'Video/GTA 5 Trailer .mp4', 'OS: Windows 10; CPU: Intel i5-3470; RAM: 8 GB; GPU: GTX 660; Storage: 110 GB', 'OS: Windows 10; CPU: Intel i7-4770; RAM: 16 GB; GPU: GTX 1060; Storage: 110 GB', 'Explore Los Santos in a modern open-world crime epic.', 4.7),
(4, 'VALORANT', 'images/Valorant.jpg', 'A 5v5 character-based tactical FPS.', 'Shooter / Tactical', 'Free', 'Video/VALORANT TRAILER.mp4', 'OS: Windows 10; CPU: Intel i3-4150; RAM: 4 GB; GPU: Intel HD 4000; Storage: 30 GB', 'OS: Windows 10; CPU: Intel i5-9400F; RAM: 8 GB; GPU: GTX 1050 Ti; Storage: 30 GB', 'Compete in precise team-based firefights.', 4.6),
(5, 'Far Cry 6', 'images/Far Cry 6.jpg', 'Fight against a modern-day dictatorship in the tropical island of Yara.', 'Shooter / Open World', 'Free', 'Video/Far Cry 6 TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-4460; RAM: 8 GB; GPU: GTX 960; Storage: 80 GB', 'OS: Windows 10; CPU: Intel i7-7700; RAM: 16 GB; GPU: GTX 1080; Storage: 80 GB', 'Lead a modern-day guerrilla revolution to liberate the island nation of Yara.', 4.2),
(6, 'ARK', 'images/ARK.jpeg', 'Survive, tame, and build in a prehistoric world.', 'Survival / Adventure', 'Free', 'Video/ARK.mp4', 'OS: Windows 10; CPU: Intel i5-2400; RAM: 8 GB; GPU: GTX 670; Storage: 60 GB', 'OS: Windows 10; CPU: Intel i7-4770; RAM: 16 GB; GPU: GTX 980; Storage: 60 GB', 'Survive on an island full of dinosaurs.', 4.0),
(7, 'Uncharted 4', 'images/Uncharted 4.jpg', 'A globe-trotting adventure of treasure and betrayal.', 'Action / Adventure', 'Free', 'Video/UNCHARTED-4 TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-8400; RAM: 8 GB; GPU: GTX 960; Storage: 70 GB', 'OS: Windows 10; CPU: Intel i7-8700; RAM: 16 GB; GPU: GTX 1070; Storage: 70 GB', 'Nathan Drake returns for one final hunt.', 4.5),
(8, 'Elden Ring', 'images/Elden-Ring.jpg', 'Explore a vast fantasy realm of danger and discovery.', 'Action / RPG', 'Free', 'Video/ELDEN RING TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-8400; RAM: 12 GB; GPU: GTX 1060; Storage: 60 GB', 'OS: Windows 10; CPU: Intel i7-8700; RAM: 16 GB; GPU: RTX 2060; Storage: 60 GB', 'Traverse the Lands Between and forge your path.', 4.9),
(9, 'Dead by Daylight', 'images/Dead-by-Daylight.png', 'Survive the horror or become the hunter.', 'Horror / Multiplayer', 'Free', 'Video/Dead by Daylight TRAILER.mp4', 'OS: Windows 10; CPU: Intel i3-4170; RAM: 8 GB; GPU: GTX 460; Storage: 50 GB', 'OS: Windows 10; CPU: Intel i7-3770; RAM: 16 GB; GPU: GTX 760; Storage: 50 GB', 'A multiplayer asymmetrical horror experience.', 4.1),
(10, 'GTA V Enhanced', 'icons/Grand Theft Auto V.png', 'Enhanced edition of the modern crime classic.', 'Action / Adventure', 'Free', 'Video/GTA 5 Trailer .mp4', 'OS: Windows 10; CPU: Intel i5-3470; RAM: 8 GB; GPU: GTX 660; Storage: 110 GB', 'OS: Windows 10; CPU: Intel i7-4770; RAM: 16 GB; GPU: GTX 1060; Storage: 110 GB', 'A refreshed version of Grand Theft Auto V.', 4.7),
(11, 'F1 25', 'icons/F125.JPEG', 'High-speed racing with the latest Formula 1 thrills.', 'Racing / Sports', 'Free', 'Video/F1-25 TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-9600K; RAM: 8 GB; GPU: GTX 970; Storage: 80 GB', 'OS: Windows 10; CPU: Intel i7-10700K; RAM: 16 GB; GPU: RTX 2060; Storage: 80 GB', 'Compete on the world''s fastest tracks.', 4.3),
(12, 'Stellar Blade', 'icons/stellar.png', 'Fast-paced sci-fi combat with cinematic style.', 'Action / RPG', 'Free', 'Video/Stellar Blade TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-7600K; RAM: 8 GB; GPU: GTX 1060; Storage: 50 GB', 'OS: Windows 10; CPU: Intel i7-9700K; RAM: 16 GB; GPU: RTX 2070; Storage: 50 GB', 'Battle across a devastated future Earth.', 4.4),
(13, 'Fortnite', 'images/Fortnite.jpg', 'A massive battle royale with constant updates.', 'Shooter / Battle Royale', 'Free', 'Video/Fortnite TRAILER.mp4', 'OS: Windows 10; CPU: Core i3-3225; RAM: 8 GB; GPU: Intel HD 4000; Storage: 30 GB', 'OS: Windows 10; CPU: Core i5-7300U; RAM: 16 GB; GPU: GTX 960; Storage: 30 GB', 'Drop in and survive to be the last one standing.', 4.6),
(14, 'Rocket League', 'icons/ROCKET.png', 'Soccer meets rocket-powered cars.', 'Sports / Racing', 'Free', 'Video/Rocket League TRAILER.mp4', 'OS: Windows 10; CPU: Intel i3-4005U; RAM: 4 GB; GPU: Intel HD 4000; Storage: 20 GB', 'OS: Windows 10; CPU: Intel i5-4690; RAM: 8 GB; GPU: GTX 1060; Storage: 20 GB', 'Score goals at high speed with your team.', 4.5),
(15, 'Football Manager 2024', 'icons/FM24.png', 'Take control of a club and shape its future.', 'Simulation / Sports', 'Free', 'Video/Football TRAILER.mp4', 'OS: Windows 10; CPU: Intel i3-530; RAM: 4 GB; GPU: Intel HD 4000; Storage: 7 GB', 'OS: Windows 10; CPU: Intel i5-9600; RAM: 8 GB; GPU: GTX 970; Storage: 7 GB', 'Manage tactics, transfers, and glory.', 4.2),
(16, 'Genshin Impact', 'icons/GEN.PNG', 'Explore a vibrant fantasy world full of elemental magic.', 'Action / RPG', 'Free', 'Video/Genshin Impact TRAILER.mp4', 'OS: Windows 10; CPU: Intel Core i5; RAM: 8 GB; GPU: GTX 1030; Storage: 30 GB', 'OS: Windows 10; CPU: Intel Core i7; RAM: 16 GB; GPU: RTX 2060; Storage: 30 GB', 'Embark on a journey across Teyvat.', 4.4),
(17, 'MotoGP 25', 'icons/motogp25.png', 'The next chapter of elite motorcycle racing.', 'Racing / Sports', 'Free', 'Video/MotoGP 25 Trailer.mp4', 'OS: Windows 10; CPU: Intel i5-2500K; RAM: 8 GB; GPU: GTX 960; Storage: 35 GB', 'OS: Windows 10; CPU: Intel i7-8700; RAM: 16 GB; GPU: RTX 2060; Storage: 35 GB', 'Race the official MotoGP season.', 4.1),
(18, 'Dying Light: The Beast', 'icons/DYING.png', 'Survive the undead in a brutal open world.', 'Horror / Survival', 'Free', 'Video/Dying Light TRAILER.mp4', 'OS: Windows 10; CPU: Intel i5-2500; RAM: 8 GB; GPU: GTX 780; Storage: 40 GB', 'OS: Windows 10; CPU: Intel i7-8700; RAM: 16 GB; GPU: GTX 1070; Storage: 40 GB', 'Parkour, survival, and zombies collide.', 4.2),
(19, 'Tides of Annihilation', 'icons/TIDES.png', 'A cinematic action journey through broken worlds.', 'Action / Adventure', 'Free', 'Video/Tides of Annihilation TREILER.mp4', 'OS: Windows 10; CPU: Intel i5-8400; RAM: 8 GB; GPU: GTX 1060; Storage: 50 GB', 'OS: Windows 10; CPU: Intel i7-10700; RAM: 16 GB; GPU: RTX 2060; Storage: 50 GB', 'Fight through a mythic world under siege.', 4.0),
(20, 'MONGIL: STAR DIVE', 'icons/MONGIL.png', 'A fantasy adventure with team-based combat.', 'RPG / Adventure', 'Free', 'Video/MONGIL TREILER.mp4', 'OS: Windows 10; CPU: Intel i5-6400; RAM: 8 GB; GPU: GTX 960; Storage: 40 GB', 'OS: Windows 10; CPU: Intel i7-8700; RAM: 16 GB; GPU: RTX 2060; Storage: 40 GB', 'A colorful adventure in a living fantasy universe.', 4.0),
(21, 'Resident Evil Requiem', 'icons/RDE.png', 'Classic survival horror with modern intensity.', 'Horror / Survival', 'Free', 'Video/Resident Evil Trailer.mp4', 'OS: Windows 10; CPU: Intel i5-4460; RAM: 8 GB; GPU: GTX 760; Storage: 40 GB', 'OS: Windows 10; CPU: Intel i7-7700; RAM: 16 GB; GPU: GTX 1070; Storage: 40 GB', 'Face an all-new nightmare.', 4.5)
on conflict (id) do update
set title = excluded.title,
    image = excluded.image,
    description = excluded.description,
    category = excluded.category,
    price = excluded.price,
    media_url = excluded.media_url,
    min_requirement = excluded.min_requirement,
    max_requirement = excluded.max_requirement,
    story = excluded.story,
    rating = excluded.rating;
